### ISSUE TITLE
Highlight cells on board on mouse over

### ISSUE THREAD

**Issue by gvsmirnov** [drewblaisdell/conway#1]
When the user hovers "CELLS ON BOARD", either his own, or in the "players online" table, these cells should be highlighted on the field. Possibly, the rest of the field can be dimmed.

**Comment by drewblaisdell** [comment]
Great idea. I'll add this to the list and hopefully implement it soon.

**Comment by drewblaisdell** [comment]
@gvsmirnov This has been implemented, pushed, and is live on http://lifecompetes.com. Thanks for the idea.
