### ISSUE TITLE
Yo drew life is down 😭

### ISSUE THREAD

**Issue by spncr** [drewblaisdell/conway#13]
Looks like your socket.io service is down?
![Screen Shot 2021-10-27 at 13 15 31](https://user-images.githubusercontent.com/1162736/139140311-fe5ecd56-8b11-4f0b-b461-57fb520e8bf8.png)

**Comment by xp2-882030kgz010602** [comment]
Can confirm

**Comment by spncr** [comment]
Looks like it is back now 👻
