### ISSUE TITLE
app.gameClient.placeLiveCells([1,2]) stops server

### ISSUE THREAD

**Issue by ghost** [drewblaisdell/conway#7]
When I executed:

```
app.gameClient.placeLiveCells([1,2])
```

server stopped to respond. I don't know if I caused it or it was just a coincidence but I decided not to try it again.

**Comment by drewblaisdell** [comment]
Fixed: https://github.com/drewblaisdell/conway/commit/0a1710b347f197fbe4105cd5ea72e7e764fd6f7d
