### ISSUE TITLE
Sending "place_live_cells" message with out-of-bounds coordinates crashes server

### ISSUE THREAD

**Issue by sf17k** [drewblaisdell/conway#8]
Discovered this while running my own server in order to develop a custom client.

App crashes in Game.placeCells() at `cell.set('alive', true);` because cell=false. I noticed Grid.getCell() clamps negative coordinates to zero, but does not check upper bounds.

**Comment by drewblaisdell** [comment]
Good catch! Bad clients could easily crash the server this way.

Fixed with this commit: https://github.com/drewblaisdell/conway/commit/59040b5cf042ae30aba85b113d86a02effc2cbe5
